### PR TITLE
Direct call enhancement - more phone numbers 

### LINKED ISSUE #155: Add visual indicator on mobile for the text that support direct call & sending emails
There are pages (e.g. https://test.cemafac.ro/pentru-cei-care-ofera-ajutor ) that contain phone numbers or email addresses.
E.g.  "Cum puteți beneficia de ajutor:
0758 119 314
consiliere@estuar.org"
On mobile, when the user presses on the phone number or email (s)he can make a direct call or send an email.
Still, there is no visual indicator in UI for the user that an action is supported

Phone Number and email

### LINKED ISSUE #163: Add visual indicator on mobile for the text that support direct call (2)
There are pages that contain phone numbers or email addresses.
On mobile (Galaxy S5, Andriod) when the user presses on the phone number or email (s)he can make a direct call or send an email.
Still, there is no visual indicator in UI for the user that an action is supported

Phone numbers:

Page: Transmitere și simptome (https://test.cemafac.ro/)
Section:"Dacă ai simptome, sau dacă ai nevoie de informații" (bottom of the page)
Text: "TelVerde la numărul 0800.800.358", "linia special dedicată lor +4021.320.20.20."

Page: https://test.cemafac.ro/cum-ne-protejam/plan-actiune-acasa
Text: "TelVerde 0800 800 358"

Page: https://test.cemafac.ro/intrebari-frecvente
Section: Ce să fac dacă am avut contact direct cu o persoană confirmată cu COVID-19?
Text: "Contactați autoritățile la linia TELVERDE 0800 800 358"

Page: https://test.cemafac.ro/intrebari-frecvente
Section: Ce pot face persoanele ce prezintă risc ridicat de îmbolnăvire?
Text: "contactați 112"

Page: https://test.cemafac.ro/intrebari-frecvente
Section: Care sunt simptomele COVID-19?
Text: "112"

### PR DESCRIPTION
**Pull request by redecs**
Closes #163 

Missed some phone numbers in my previous pull request for #155. Fixed now.

### CODE REVIEW

**Comment by aniri** [comment]
> I doesn't like it as a `<a>` 
> Screenshot 2020-03-28 at 15 48 13

@moonflare :eyes: good catch!

maybe we could add an issue in the components repo to enhance that component to accept html content?

**Comment by moonflare** [comment]
> > I doesn't like it as a `<a>`
> > Screenshot 2020-03-28 at 15 48 13
> 
> @moonflare 👀 good catch!
> 
> maybe we could add an issue in the components repo to enhance that component to accept html content? is that possible?

I think the way to go will be to do it similar to the other type of contents. Where we convert it to HTML outside the component. I'll check real quick.

**Comment by redecs** [comment]
@moonflare oops, sorry for that... didn't notice the form. I see there's a `// TODO: use a real component for this` in the component. How should I proceed?

**Comment by moonflare** [comment]
> @moonflare oops, sorry for that... didn't notice the form. I see there's a `// TODO: use a real component for this` in the component. How should I proceed?

We now have that component [here](https://taskforce-fe-components.now.sh/?path=/story/listitem--with-non-option-state), but you might have to pass the title to the component something like below. Also we might have to wrap the `label` text with `<p>`, I believe, for the questions with `type: "FINAL"`

```js
title={
  <div
    dangerouslySetInnerHTML={{ __html: accordionData.content }}
   />
 }
```

**Comment by redecs** [comment]
@moonflare used the ListItem component and it works with the `<p/>` wrapping of the label, removed the option state (thanks for the Storybook link it was really handy). 
Looks good know. 
Please let me know if it's OK (very limited experience with React).

**Comment by redecs** [comment]
@moonflare I though I addressed that here: https://github.com/code4romania/ce-ma-fac/pull/164/commits/03d09a62e2d7b2c427a7296ecafeeb45f55084dc Am I missing something?

**Comment by moonflare** [comment]
> @moonflare I though I addressed that here: [03d09a6](https://github.com/code4romania/ce-ma-fac/commit/03d09a62e2d7b2c427a7296ecafeeb45f55084dc) Am I missing something?

Hmm. I was referring to [this](https://github.com/code4romania/ce-ma-fac/blob/develop/frontend/src/components/Form/Form.scss#L6#L11) part. We don't need it anymore as we're using the component now.

**Comment by redecs** [comment]
@moonflare cleanup done. thanks!

**Pull request merged**
